"""Add csv_file_path to Campaign model

Revision ID: 2ee6b74dcfac
Revises: c97c731619bc
Create Date: 2024-10-31 13:35:48.683080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee6b74dcfac'
down_revision = 'c97c731619bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('csv_file_path', sa.String(), nullable=False))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('csv_file_path')

    # ### end Alembic commands ###
